### ISSUE TITLE
Added frameWidth, frameHeight track stats

### ISSUE THREAD

**Issue by pallab-gain** [ObserveRTC/observer#61]
Can we please add `frameWidth` and `frameHeight` in the track stats?

I think [track](https://www.w3.org/TR/webrtc-stats/#dom-rtcstatstype-track) has been marked as obsoleted but some browser vendors still report them, and they are kind of important. Do you have different opinion or what you think about it ?

**Comment by pallab-gain** [comment]
Relevant PR from observer-s https://github.com/ObserveRTC/observer-js/pull/51

**Comment by pallab-gain** [comment]
Any update on adding these two stats, or some feedback?

**Comment by balazskreith** [comment]
The Report schema is changed, therefore subsequent processing element need to use the new Report schema
